"use client"

import { DynamicFrameLayout } from "./components/dynamic-frame-layout"

const demoFrames = [
  {
    id: 1,
    video: "https://assets.mixkit.co/videos/21607/21607-720.mp4",
    title: "UNICUM",
    fontClass: "font-[var(--font-jetbrains-mono)] text-4xl",
    defaultPos: { x: 0, y: 0, w: 4, h: 4 },
    corner: "",
    edgeHorizontal: "",
    edgeVertical: "",
    mediaSize: 1,
    borderThickness: 4,
    borderSize: 90,
    isHovered: false,
  },
  {
    id: 2,
    video: "https://assets.mixkit.co/videos/5396/5396-720.mp4",
    title: "ONTWIKKELING AI",
    fontClass: "font-[var(--font-oswald)] text-4xl font-medium uppercase tracking-wider",
    defaultPos: { x: 4, y: 0, w: 4, h: 4 },
    corner: "",
    edgeHorizontal: "",
    edgeVertical: "",
    mediaSize: 1,
    borderThickness: 4,
    borderSize: 90,
    isHovered: false,
  },
  {
    id: 3,
    video: "https://assets.mixkit.co/videos/13312/13312-720.mp4",
    title: "CHINA",
    fontClass: "font-[var(--font-creepster)] text-4xl",
    defaultPos: { x: 8, y: 0, w: 4, h: 4 },
    corner: "",
    edgeHorizontal: "",
    edgeVertical: "",
    mediaSize: 1,
    borderThickness: 4,
    borderSize: 90,
    isHovered: false,
  },
  {
    id: 4,
    video: "https://assets.mixkit.co/videos/1728/1728-720.mp4",
    title: "SOFTWARE",
    fontClass: "font-[var(--font-archivo-black)] text-5xl tracking-wide",
    defaultPos: { x: 0, y: 4, w: 4, h: 4 },
    corner: "",
    edgeHorizontal: "",
    edgeVertical: "",
    mediaSize: 1,
    borderThickness: 4,
    borderSize: 90,
    isHovered: false,
  },
  {
    id: 5,
    video: "https://static.cdn-luma.com/files/58ab7363888153e3/Logo%20Exported.mp4",
    title: "ALJU",
    fontClass: "font-[var(--font-bebas-neue)] text-5xl uppercase tracking-wide",
    defaultPos: { x: 4, y: 4, w: 4, h: 4 },
    corner: "",
    edgeHorizontal: "",
    edgeVertical: "",
    mediaSize: 1,
    borderThickness: 4,
    borderSize: 90,
    isHovered: false,
  },
  {
    id: 6,
    video: "https://assets.mixkit.co/videos/50749/50749-720.mp4",
    title: "AI AGENTS",
    fontClass: "font-[var(--font-jetbrains-mono)] text-3xl tracking-widest",
    defaultPos: { x: 8, y: 4, w: 4, h: 4 },
    corner: "",
    edgeHorizontal: "",
    edgeVertical: "",
    mediaSize: 1,
    borderThickness: 4,
    borderSize: 90,
    isHovered: false,
  },
  {
    id: 7,
    video: "https://assets.mixkit.co/videos/14395/14395-720.mp4",
    title: "AI=UI ",
    fontClass: "font-[var(--font-merriweather)] text-3xl italic font-light",
    defaultPos: { x: 0, y: 8, w: 4, h: 4 },
    corner: "",
    edgeHorizontal: "",
    edgeVertical: "",
    mediaSize: 1,
    borderThickness: 4,
    borderSize: 90,
    isHovered: false,
  },
  {
    id: 8,
    video: "https://assets.mixkit.co/videos/9339/9339-720.mp4",
    title: "LLM'S",
    fontClass: "font-[var(--font-dancing-script)] text-4xl",
    defaultPos: { x: 4, y: 8, w: 4, h: 4 },
    corner: "",
    edgeHorizontal: "",
    edgeVertical: "",
    mediaSize: 1,
    borderThickness: 4,
    borderSize: 90,
    isHovered: false,
  },
  {
    id: 9,
    video: "https://video-previews.elements.envatousercontent.com/429e6b1a-6631-44c3-9798-f873016d46e3/watermarked_preview/watermarked_preview.mp4",
    title: "DATA",
    fontClass: "font-[var(--font-caprasimo)] text-4xl tracking-tight",
    defaultPos: { x: 8, y: 8, w: 4, h: 4 },
    corner: "",
    edgeHorizontal: "",
    edgeVertical: "",
    mediaSize: 1,
    borderThickness: 4,
    borderSize: 90,
    isHovered: false,
  },
]

export default function ToekomstPage() {
  return (
    <div className="h-screen w-screen bg-zinc-900">
      <DynamicFrameLayout 
        frames={demoFrames} 
        className="w-full h-full" 
        hoverSize={6}
        gapSize={4}
      />
    </div>
  )
}