import type { Metadata } from "next";
import { 
  Geist, 
  Geist_Mono, 
  Oswald, 
  Merriweather, 
  Archivo_Black, 
  Bebas_Neue, 
  Dancing_Script, 
  Caprasimo,
  JetBrains_Mono,
  Creepster
} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Unique fonts for titles
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["500"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["400"],
  style: ["italic"],
});

const archivoBlack = Archivo_Black({
  variable: "--font-archivo-black",
  subsets: ["latin"],
  weight: ["400"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: ["400"],
});

const dancingScript = Dancing_Script({
  variable: "--font-dancing-script",
  subsets: ["latin"],
  weight: ["400"],
});

const caprasimo = Caprasimo({
  variable: "--font-caprasimo",
  subsets: ["latin"],
  weight: ["400"],
});

// Alternative fonts that are available
const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["400"],
});

const creepster = Creepster({
  variable: "--font-creepster",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${oswald.variable} ${merriweather.variable} ${archivoBlack.variable} ${bebasNeue.variable} ${dancingScript.variable} ${caprasimo.variable} ${jetbrainsMono.variable} ${creepster.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
